<?php if ( ! defined('BASEPATH')) exit('No direct script access allowed'); 

$modules = array(
	'fancyupload' => 'Fancyupload',
	'search' => 'Search',
	'users' => 'Usermanager',
	'simpleform' => 'Simpleform'
	);

$aliases = array(

	);



/* End of file modules.php */
/* Auto generated by Themes Administration on : 2011.08.08 18:22:41 */
/* Location: /home/be3/Development/ionize/application//config/modules.php */
